version: '3.8'
services:
  mongo-rs0-arbiter:
    image: mongo:latest
    hostname: mongo-rs0-arbiter
    container_name: mongo-rs0-arbiter
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./rs_0_arbiter/data:/data
      - ./rs_0_arbiter/log:/var/log/mongodb
      - ./rs_0_arbiter/mongos.conf:/etc/mongos.conf
      - ./mongodb.key:/etc/mongodb.key
    command:
      - '--config'
      - '/etc/mongos.conf'
      - '--keyFile'
      - '/etc/mongodb.key'
    network_mode: host

  mongo-rs1-arbiter:
    image: mongo:latest
    hostname: mongo-rs1-arbiter
    container_name: mongo-rs1-arbiter
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./rs_1_arbiter/data:/data
      - ./rs_1_arbiter/log:/var/log/mongodb
      - ./rs_1_arbiter/mongos.conf:/etc/mongos.conf
      - ./mongodb.key:/etc/mongodb.key
    command:
      - '--config'
      - '/etc/mongos.conf'
      - '--keyFile'
      - '/etc/mongodb.key'
    network_mode: host

  mongo-config:
    image: mongo:latest
    hostname: mongo-config
    container_name: mongo-config
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./mongo_config/data:/data
      - ./mongo_config/log:/var/log/mongodb
      - ./mongo_config/mongos.conf:/etc/mongos.conf
      - ./mongodb.key:/etc/mongodb.key
    command:
      - '--config'
      - '/etc/mongos.conf'
      - '--keyFile'
      - '/etc/mongodb.key'
    network_mode: host

